source "https://rubygems.org"
ruby "2.5.1"

gem "autoprefixer-rails"
gem "browser-timezone-rails"
gem "cancancan", "~> 2.0"
gem "coffee-rails"
gem "delayed_job_active_record"
gem "daemons"
gem "dynamic_form"
gem "faraday_middleware"
gem "foundation-rails"
gem "foundation-icons-sass-rails"
gem "google-api-client", ">= 0.4.4", :require => "google/api_client"
gem "gon"
gem "high_voltage", "~> 3.1"
gem "httparty"
gem "jquery-rails"
gem "jquery-ui-rails"
gem "js_cookie_rails"
gem "json"
gem "jwt", "~>1.4.0"
gem "kaminari"
gem "modernizr-rails"
gem "newrelic_rpm"
gem "omniauth-google-oauth2"
gem "omniauth", ">= 1.1.3"
gem "oj"
gem "pg", "~> 0.20.0"
gem "rails", "5.2.1"
gem "responders", "~> 2.0"
gem "rolify", ">= 3.2.0"
gem "sass-rails"
gem "sendgrid-ruby"
gem "simple_form", ">= 2.0.4"
gem "split-analytics"
gem "split", require: "split/dashboard"
gem "stripe"
gem "turbolinks", "~> 5.1.0"
gem "uglifier"
gem "workless"
gem "zocial-rails"

gem "rollbar", require: false
gem "puma"
gem "rack-timeout"

group :development, :test do
  gem "dotenv-rails", require: "dotenv/rails-now"
  gem "pry-rails"
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "bundle-audit"
end

group :test do
  gem "capybara"
  gem "chromedriver-helper"
  gem "codacy-coverage"
  gem "email_spec", ">= 1.4.0"
  gem "rails-controller-testing"
  gem "rspec_junit_formatter"
  gem "selenium-webdriver"
end

group :development do
  gem "binding_of_caller", ">= 0.7.1"
  gem "better_errors", ">= 0.6.0"
  gem "letter_opener"
  gem "thor"
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem "web-console", ">= 3.3.0"
  gem "listen", ">= 3.0.5", "< 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end
