# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
SENDGRID_USERNAME: approveforme
SENDGRID_PASSWORD: afm12345
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
OMNIAUTH_PROVIDER_KEY: Your_OmniAuth_Provider_Key
OMNIAUTH_PROVIDER_SECRET: Your_OmniAuth_Provider_Secret
ROLES: [admin, user, VIP]
GOOGLE_SCOPE: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.install
development:
 GOOGLE_ID: 107940143634.apps.googleusercontent.com
 GOOGLE_SECRET: n1adtCS9usCvQkxPzEspTYAA
 REDIRECT_URI: http://localhost:3000/auth/google_oauth2/callback
 APP_ID: 107940143634
 REDISTOGO_URL: redis://localhost:6379
test:
 GOOGLE_ID: 107940143634.apps.googleusercontent.com
 GOOGLE_SECRET: n1adtCS9usCvQkxPzEspTYAA
 REDIRECT_URI: http://localhost:3000/auth/google_oauth2/callback
 APP_ID: 107940143634
 REDISTOGO_URL: redis://localhost:6379
production:
 GOOGLE_ID: 291418161965-gmlrl8jb64dvprch5pf8c7eg4j3b9tgh.apps.googleusercontent.com
 GOOGLE_SECRET: _JoKuvjEBXsHyaTwFjxWE7WS
 REDIRECT_URI: http://limitless-cove-8731.herokuapp.com/oauth2callback
 APP_ID: 107940143634
 REDISTOGO_URL: redis://redistogo:808e3c04b0af3d8f5141fb00d8e6685f@beardfish.redistogo.com:9041/