default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: approveforme_development

test:
  <<: *default
  username: approveforme
  database: approveforme_test

production:
  <<: *default
  database: approveforme_production
  username: approveforme
  password: <%= ENV['APPROVEFORME_DATABASE_PASSWORD'] %>
