default: &default
  lite:
    name: Lite
    reviews_each_month: 2
    reviews_each_month_in_words: 2
    order: 1
    monthly:
      identifier: plan_DTIkcAtbqCDfXV
      price: 0
      price_in_words: FREE
    yearly:
      identifier: plan_DTIlyIz8yKRWg2
      price: 0
      price_in_words: FREE
    extra-details:
      - Upload files from Google Drive
      - Online Support
  professional:
    name: Professional
    reviews_each_month: 6
    reviews_each_month_in_words: 6
    order: 2
    monthly:
      identifier: plan_DTImhtH6M35W2j
      price: 200
      price_in_words: $2/mo
    yearly:
      identifier: plan_DTImTvSDRQYraG
      price: 2000
      price_in_words: $20/yr
    extra-details:
      - Upload files from Google Drive
      - Set deadline time
      # - Intelligent Reminders
      - Online Support
  unlimited:
    name: Unlimited
    reviews_each_month: 1000000
    reviews_each_month_in_words: Unlimited
    order: 3
    monthly:
      identifier: plan_DTIoNcoR76M1AE
      price: 500
      price_in_words: $5/mo
    yearly:
      identifier: plan_DTIoxM2Si5Mq9d
      price: 5500
      price_in_words: $55/yr
    extra-details:
      - Upload files from Google Drive
      - Set deadline time
      # - Intelligent Reminders
      # - Google Analytics
      - Online Support


development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  lite:
    identifier: prod_DTIhAVaKj6zTRV
    name: Lite
    reviews_each_month: 2
    reviews_each_month_in_words: 2
    order: 1
    monthly:
      identifier: plan_DTIh8GdKV8PD3O
      price: 0
      price_in_words: FREE
    yearly:
      identifier: plan_DUn1gBlfIf0k1K
      price: 0
      price_in_words: FREE
    extra-details:
      - Upload files from Google Drive
      - Online Support
  professional:
    identifier: prod_DUn3zIzQlTXsUW
    name: Professional
    reviews_each_month: 6
    reviews_each_month_in_words: 6
    order: 2
    monthly:
      identifier: plan_DUnWe8RyBEZrWv
      price: 200
      price_in_words: $2/mo
    yearly:
      identifier: plan_EMMO3TXG8TlkmM
      price: 2000
      price_in_words: $20/yr
    extra-details:
      - Upload files from Google Drive
      - Set deadline time
      # - Intelligent Reminders
      - Online Support
  unlimited:
    identifier: prod_DTIhAVaKj6zTRV
    name: Unlimited
    reviews_each_month: 1000000
    reviews_each_month_in_words: Unlimited
    order: 3
    monthly:
      identifier: plan_DUnbZC2d2aIkLq
      price: 500
      price_in_words: $5/mo
    yearly:
      identifier: plan_DUncYNajGsX5fq
      price: 5500
      price_in_words: $55/yr
    extra-details:
    - Upload files from Google Drive
    - Set deadline time
    # - Intelligent Reminders
    # - Google Analytics
    - Online Support
