---
:verbose: false
:concurrency: 5

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8

# Be careful when increasing the `critical` queue as race conditions may crop up
:queues:
  - critical
  - rollbar
  - default
  - mailers

# you can override concurrency based on environment
production:
  :concurrency: 3
staging:
  :concurrency: 3